<?php

/**
 * @file
 * Install, update and uninstall functions for the DevPanel Marketplace Bar module.
 */

use Drupal\devpanel_marketplace_bar\Helper\ApiHelper;

/**
 * Implements hook_install().
 */
function devpanel_marketplace_bar_install() {
  // Fetch initial data on install.
  ApiHelper::fetchAndSaveData();
}


/**
 * Re-fetch marketplace data to apply the new API logic.
 */
function devpanel_marketplace_bar_update_10001() {
  ApiHelper::fetchAndSaveData();
}
